services:
  app:
    container_name: app
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:cached
    depends_on:
      - localstack
    command: sleep infinity
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://localstack:4566

  localstack:
    container_name: localstack-main
    image: localstack/localstack
    ports:
      - 4566:4566            
      - 4510-4559:4510-4559  # external services port range
    env_file:
      - .env
    volumes:
      - localstack_data:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/health"]


volumes:
  localstack_data: 