AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "Hono App"

Parameters:
  StageName:
    Type: String
    Default: v1
    Description: "API Gateway stage name"

Globals:
  Function:
    Timeout: 3

Resources:
  # API Gateway
  HonoApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName

  # Secrets Manager
  HonoSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "hono-${StageName}"
      Description: "Hono secret"
      SecretString: !Sub '{"name": "hono-api", "email": "hono@hono.com"}'

  # Lambda Function
  HonoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: index.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Events:
        Index:
          Type: Api
          Properties:
            Path: /
            Method: GET
            RestApiId: !Ref HonoApi
        Hello:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
            RestApiId: !Ref HonoApi
        GetSecretValue:
          Type: Api
          Properties:
            Path: /get-secret-value
            Method: GET
            RestApiId: !Ref HonoApi
        # All:
        #   Type: Api
        #   Properties:
        #     Path: /{proxy+}
        #     Method: ANY
        #     RestApiId: !Ref HonoApi
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/index.ts

Outputs:
  StageName:
    Description: "API Gateway stage name"
    Value: !Ref StageName
  LocalStackApi:
    Description: "LocalStack API Gateway endpoint URL"
    Value: !Sub "http://localhost:4566/restapis/${HonoApi}/${StageName}/_user_request_/"
  AWSLambdaApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${HonoApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/"
  Function:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HonoFunction.Arn
  FunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HonoFunctionRole.Arn
